config/routes.rb
Rails.application.routes.draw do
  resources :taboo_words
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "home#index"

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/taboo_word.rb
class TabooWord < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/taboo_words_controller.rb
class TabooWordsController < ApplicationController
  before_action :set_taboo_word, only: %i[ show edit update destroy ]

  # GET /taboo_words or /taboo_words.json
  def index
    @taboo_words = TabooWord.all
  end

  # GET /taboo_words/1 or /taboo_words/1.json
  def show
  end

  # GET /taboo_words/new
  def new
    @taboo_word = TabooWord.new
  end

  # GET /taboo_words/1/edit
  def edit
  end

  # POST /taboo_words or /taboo_words.json
  def create
    @taboo_word = TabooWord.new(taboo_word_params)

    respond_to do |format|
      if @taboo_word.save
        format.html { redirect_to taboo_word_url(@taboo_word), notice: "Taboo word was successfully created." }
        format.json { render :show, status: :created, location: @taboo_word }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @taboo_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /taboo_words/1 or /taboo_words/1.json
  def update
    respond_to do |format|
      if @taboo_word.update(taboo_word_params)
        format.html { redirect_to taboo_word_url(@taboo_word), notice: "Taboo word was successfully updated." }
        format.json { render :show, status: :ok, location: @taboo_word }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @taboo_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taboo_words/1 or /taboo_words/1.json
  def destroy
    @taboo_word.destroy

    respond_to do |format|
      format.html { redirect_to taboo_words_url, notice: "Taboo word was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_taboo_word
      @taboo_word = TabooWord.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def taboo_word_params
      params.require(:taboo_word).permit(:main_word, :secondary_word1, :secondary_word2, :secondary_word3, :secondary_word4, :secondary_word5)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/taboo_words_helper.rb
module TabooWordsHelper
end

app/views/home/index.html.erb
<h1>Welcome to web_games</h1>
<p>See below for the list of games currently available.</p>

<ul>
  <%= link_to "Taboo", taboo_words_path %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebGames</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/taboo_words/_form.html.erb
<%= form_with(model: taboo_word) do |form| %>
  <% if taboo_word.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(taboo_word.errors.count, "error") %> prohibited this taboo_word from being saved:</h2>

      <ul>
        <% taboo_word.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :main_word, style: "display: block" %>
    <%= form.text_field :main_word %>
  </div>

  <div>
    <%= form.label :secondary_word1, style: "display: block" %>
    <%= form.text_field :secondary_word1 %>
  </div>

  <div>
    <%= form.label :secondary_word2, style: "display: block" %>
    <%= form.text_field :secondary_word2 %>
  </div>

  <div>
    <%= form.label :secondary_word3, style: "display: block" %>
    <%= form.text_field :secondary_word3 %>
  </div>

  <div>
    <%= form.label :secondary_word4, style: "display: block" %>
    <%= form.text_field :secondary_word4 %>
  </div>

  <div>
    <%= form.label :secondary_word5, style: "display: block" %>
    <%= form.text_field :secondary_word5 %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/taboo_words/_taboo_word.html.erb
<style>
  .taboo-card {
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    border-radius: 15px;
    width: 200px;
    padding: 5px;
    border: 1px solid red;
    text-align: center;
    background-image: linear-gradient(30deg, rgba(123, 222, 245, 1), rgba(242, 114, 196, 1));
  }

  .taboo-card:hover {
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
  }

  .main-word {
    text-decoration-line: underline;
    text-decoration-color: blue;
    font-size: 1.5rem;
  }

  .secondary_word {
    text-decoration-line: overline;
    text-decoration-color: red;
  }
</style>
<div id="<%= dom_id taboo_word %>" class="taboo-card">

  <p class="main-word">
  <%= taboo_word.main_word.titleize %>
  </p>

  <p class="secondary_word">
  <%= taboo_word.secondary_word1.titleize %>
  </p>
  <p class="secondary_word">
  <%= taboo_word.secondary_word2.titleize %>
  </p>
  <p class="secondary_word">
  <%= taboo_word.secondary_word3.titleize %>
  </p>
  <p class="secondary_word">
  <%= taboo_word.secondary_word4.titleize %>
  </p>
  <p class="secondary_word">
  <%= taboo_word.secondary_word5.titleize %>
  </p>

</div>

app/views/taboo_words/edit.html.erb
<h1>Editing taboo word</h1>

<%= render "form", taboo_word: @taboo_word %>

<br>

<div>
  <%= link_to "Show this taboo word", @taboo_word %> |
  <%= link_to "Back to taboo words", taboo_words_path %>
</div>

app/views/taboo_words/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Taboo words</h1>

<%= link_to "New taboo word", new_taboo_word_path %>

<style>
  #taboo_words {
    display: grid;
    place-items: center;
    grid-template-columns: 1fr;
  }
  @media screen and (min-width: 768px) {
    #taboo_words {
      grid-template-columns: 1fr 1fr 1fr;
    }
  }
</style>

<div id="taboo_words">
  <% @taboo_words.each do |taboo_word| %>
    <div>
    <%= render taboo_word %>
    <p style="text-align: center; font-size: .75rem;">
      <%= link_to "Show this taboo word", taboo_word %>
    </p>
    </div>
  <% end %>
</div>

app/views/taboo_words/new.html.erb
<h1>New taboo word</h1>

<%= render "form", taboo_word: @taboo_word %>

<br>

<div>
  <%= link_to "Back to taboo words", taboo_words_path %>
</div>

app/views/taboo_words/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @taboo_word %>

<div>
  <%= link_to "Edit this taboo word", edit_taboo_word_path(@taboo_word) %> |
  <%= link_to "Back to taboo words", taboo_words_path %>

  <%= button_to "Destroy this taboo word", @taboo_word, method: :delete %>
</div>